services:
  - type: web
    name: minecraft-hebrew-commands
    env: node
    plan: starter
    buildCommand: npm run build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"
      - key: RATE_LIMIT_MAX
        value: 100
      - key: RATE_LIMIT_WINDOW
        value: 900000
    healthCheckPath: /health
    autoDeploy: true
    region: oregon
    rootDir: .