services:
  - type: web
    name: minecraft-hebrew-commands
    env: node
    region: oregon
    plan: free
    buildCommand: cd client && npm ci && npm run build && cd ../server && npm ci
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: "*"
    healthCheckPath: /health